INSERT INTO airlines (airlineid, airlinename) VALUES (1, 'American Airlines');
INSERT INTO airlines (airlineid, airlinename) VALUES (2, 'Delta Air Lines');
INSERT INTO airlines (airlineid, airlinename) VALUES (3, 'United Airlines');
INSERT INTO airlines (airlineid, airlinename) VALUES (4, 'Southwest Airlines');
INSERT INTO airlines (airlineid, airlinename) VALUES (5, 'Emirates');
INSERT INTO airlines (airlineid, airlinename) VALUES (6, 'Lufthansa');
INSERT INTO airlines (airlineid, airlinename) VALUES (7, 'British Airways');
INSERT INTO airlines (airlineid, airlinename) VALUES (8, 'Air France');
INSERT INTO airlines (airlineid, airlinename) VALUES (9, 'Qantas Airways');
INSERT INTO airlines (airlineid, airlinename) VALUES (10, 'Singapore Airlines');
INSERT INTO airlines (airlineid, airlinename) VALUES (11, 'Cathay Pacific');
INSERT INTO airlines (airlineid, airlinename) VALUES (12, 'Qatar Airways');
INSERT INTO airlines (airlineid, airlinename) VALUES (13, 'Turkish Airlines');
INSERT INTO airlines (airlineid, airlinename) VALUES (14, 'Etihad Airways');
INSERT INTO airlines (airlineid, airlinename) VALUES (15, 'ANA (All Nippon Airways)');
INSERT INTO airlines (airlineid, airlinename) VALUES (16, 'Virgin Atlantic');
INSERT INTO airlines (airlineid, airlinename) VALUES (17, 'KLM Royal Dutch Airlines');
INSERT INTO airlines (airlineid, airlinename) VALUES (18, 'Japan Airlines');
INSERT INTO airlines (airlineid, airlinename) VALUES (19, 'Air Canada');
INSERT INTO airlines (airlineid, airlinename) VALUES (20, 'Air New Zealand');
INSERT INTO airlines (airlineid, airlinename) VALUES (21, 'Virgin Australia');
INSERT INTO airlines (airlineid, airlinename) VALUES (22, 'Swiss International Air Lines');
INSERT INTO airlines (airlineid, airlinename) VALUES (23, 'Austrian Airlines');
INSERT INTO airlines (airlineid, airlinename) VALUES (24, 'Finnair');
INSERT INTO airlines (airlineid, airlinename) VALUES (25, 'Korean Air');
INSERT INTO airlines (airlineid, airlinename) VALUES (26, 'Thai Airways');
INSERT INTO airlines (airlineid, airlinename) VALUES (27, 'Malaysia Airlines');
INSERT INTO airlines (airlineid, airlinename) VALUES (28, 'EgyptAir');
INSERT INTO airlines (airlineid, airlinename) VALUES (29, 'Aeroflot Russian Airlines');
INSERT INTO airlines (airlineid, airlinename) VALUES (30, 'Scandinavian Airlines (SAS)');
INSERT INTO airlines (airlineid, airlinename) VALUES (31, 'Norwegian Air Shuttle');
INSERT INTO airlines (airlineid, airlinename) VALUES (32, 'LATAM Airlines');
INSERT INTO airlines (airlineid, airlinename) VALUES (33, 'Iberia');
INSERT INTO airlines (airlineid, airlinename) VALUES (34, 'Garuda Indonesia');
INSERT INTO airlines (airlineid, airlinename) VALUES (35, 'Alaska Airlines');
INSERT INTO airlines (airlineid, airlinename) VALUES (36, 'JetBlue Airways');
INSERT INTO airlines (airlineid, airlinename) VALUES (37, 'Hawaiian Airlines');
INSERT INTO airlines (airlineid, airlinename) VALUES (38, 'EVA Air');
INSERT INTO airlines (airlineid, airlinename) VALUES (39, 'Azul Brazilian Airlines');
INSERT INTO airlines (airlineid, airlinename) VALUES (40, 'AirAsia');
INSERT INTO airlines (airlineid, airlinename) VALUES (41, 'IndiGo');
INSERT INTO airlines (airlineid, airlinename) VALUES (42, 'Vueling Airlines');
INSERT INTO airlines (airlineid, airlinename) VALUES (43, 'Wizz Air');
INSERT INTO airlines (airlineid, airlinename) VALUES (44, 'EasyJet');
INSERT INTO airlines (airlineid, airlinename) VALUES (45, 'Ryanair');
INSERT INTO airlines (airlineid, airlinename) VALUES (46, 'Spirit Airlines');
INSERT INTO airlines (airlineid, airlinename) VALUES (47, 'Allegiant Air');
INSERT INTO airlines (airlineid, airlinename) VALUES (48, 'Frontier Airlines');
INSERT INTO airlines (airlineid, airlinename) VALUES (49, 'Air Arabia');
INSERT INTO airlines (airlineid, airlinename) VALUES (50, 'Flydubai');
